  version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:10
      branches:
        only:
          - master
      steps:
        - add_ssh_keys:
            fingerprints:
              - "d4:3c:ed:1e:9c:10:03:f7:0d:f3:e8:cb:7e:58:6c:4e"
        - checkout
        - run:
            name: Install
            command: yarn install
        - run:
            name: Build
            command: yarn build
        - run:
            name: Prepare shell commands
            # shell chmod +x 赋予执行权限
            # 执行shell脚本
            command: chmod +x scripts/depoly.sh
        - run:
            name: Run Deploy to GithubPages
            command: ../scripts/depoly.sh