# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2
jobs:
  build:
    docker:
      - image: circle/node:10
    steps:
      - run: echo 'A first hello'
      - run: npm -v